### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Andy16k** [CatalystCash/Catalyst-Cash#1]
[ 81%] Building CXX object src/CMakeFiles/BlockchainExplorer.dir/BlockchainExplorer/BlockchainExplorerDataBuilder.cpp.o
In function ‘T CryptoNote::{anonymous}::popRandomValue(URNG&, std::vector<T>&) [with URNG = std::linear_congruential_engine<long unsigned int, 16807, 0, 2147483647>; T = long unsigned int]’:
cc1plus: error: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

**Comment by FndNur1Labs** [comment]
buffer? try update libbost and updates the installed plugin
